linuxdeepin/deepin-anything

- kernelmod/vfs_change.c
changed do_gettimeofday and timeval to ktime_get_real_ts64 and timespec64.
> fix: support for linux 5.0+

- server/lib/lftdisktool.cpp
- server/lib/lftdisktool.h
- server/lib/lftmanager.cpp
- server/lib/lftmanager.h
> refactor: rename DFMDisk/DFMBlock => DDisk/DBlock

- debian/deepin-anything-server.install
- server/tool/com.deepin.anything.service
- server/tool/deepin-anything-tool-ionice
- server/tool/deepin-anything-tool.service
- server/tool/tool.pro
Reduce the priority of IO
防止生成索引数据时将磁盘io完全占用而导致系统严重卡顿
> refactor: use ionice for deepin-anything-tool

- server/lib/lftmanager.cpp
> fix: the search results is empty on sametimes

- kernelmod/vfs_change.c
> fix: compatible with high version kernel

- archlinux/PKGBUILD
- archlinux/deepin-anything-server.sysusers
> feat: add archlinux build

- archlinux/PKGBUILD
conflict deepin-anything-dkms
Log:
> fix: conflict deepin-anything-dkms

- debian/changelog
> chore: bump debian/changelog version

- .reuse/dep5
- README.md
- README.zh_CN.md
> chore: update README

- archlinux/PKGBUILD
- kernelmod/vfs_kretprobes.c
> fix: reference local variable before assignment

- src/cli/src/stats.c
- src/kernelmod/Makefile
- src/kernelmod/arg_extractor.c
- src/kernelmod/event.c
- src/kernelmod/event_merge.c
- src/kernelmod/module.c
- src/kernelmod/vfs_fsnotify.c
- src/kernelmod/vfs_genl.c
- src/kernelmod/vfs_kretprobes.c
- src/library/src/fs_buf.c
- src/library/src/index/composite_str.c
- src/library/src/index/index_allmem.c
- src/server/backend/eventsource_genl.cpp
- src/server/backend/lib/lftmanager.cpp
- src/tools/calc_index.py
> fix: resolve compile warnings

- src/server/backend/eventsource_genl.cpp
When deepin-anything-server monitors the mount event of the fuse.dlnfs file system, it will set the unnamed devices to be monitored to the vfs_monitor kernel module, so that the events that occur on the fuse.dlnfs file system will be sent by vfs_monitor to deepin- anything-server.
log: adapt dlnfs
> feat: Support monitor events from dlnfs

- src/server/backend/lib/lftmanager.cpp
Check if the list is empty before using it.
Log: fix bug
> fix: deepin-anything-server segfault

- debian/control
fix v23 build error
Log: fix: v23 build error
> fix: v23 build error

- src/kernelmod/vfs_fsnotify.c
- src/kernelmod/vfs_kretprobes.c
On a system with audit enabled, when a privileged user mounts the fuse file system, if vfs_monitor obtains information about the fuse file system (such as through kern_path()), it will cause a system call deadlock, because the fuse daemon responding to the request Waiting for mount to complete. The solution is to not get information about mounted devices by default.
log: fix bug
> fix: Privileged user mount fuse filesystem stuck

- debian/changelog
- src/cli/Makefile
- src/cli/src/main.c
- src/library/src/fs_buf.c
- src/server/backend/server.cpp
- src/server/backend/server.h
fix: Fix search issue on dlnfs dir.
If search in less files dir, the range still was cliped as multi range with incrorect min_range. On dlnfs dir, there are always double actions, ignore the first one.
Log: Fix search issue.
>  fix: Fix search issue on dlnfs dir.

- debian/control
- src/server/backend/anythingbackend.cpp
- src/server/backend/anythingbackend.h
- src/server/backend/backend.pro
- src/server/backend/eventsource_genl.cpp
- src/server/backend/eventsource_genl.h
- src/server/backend/lib/eventadaptor.cpp
- src/server/backend/lib/eventadaptor.h
- src/server/backend/lib/lftdisktool.cpp
- src/server/backend/lib/lftdisktool.h
- src/server/backend/lib/lftmanager.cpp
- src/server/backend/lib/lftmanager.h
- src/server/backend/lib/logdefine.h
- src/server/backend/lib/logsaver.cpp
- src/server/backend/lib/logsaver.h
- src/server/backend/server.cpp
- src/server/backend/server.h
Currently, use the DLog to store log, after remove this dtk depending, implement a new log store.
Log: remove dtk depending.
> chore: Remove dtk depending and refactor log store.

- debian/changelog
- src/server/backend/backend.pro
- src/server/backend/eventsource_genl.cpp
- src/server/backend/lib/eventadaptor.cpp
- src/server/backend/lib/lftdisktool.cpp
- src/server/backend/lib/lftdisktool.h
- src/server/backend/lib/lftmanager.cpp
- src/server/backend/lib/logsaver.cpp
- src/server/backend/lib/logsaver.h
- src/server/backend/lib/mountcacher.cpp
- src/server/backend/lib/mountcacher.h
- src/server/backend/server.cpp
If the IO is busying or target is not exist anymore(e.g mount from netFS), If try use QStorageInfo API to get info, it was block at stat related system function. Use a unified mount cache and then use mount point to parse info.
Log: refactor mountinfo related.
> fix: Fix block issue if IO busying.

- README.md
- README.zh_CN.md
- src/server/backend/lib/logsaver.cpp
Did not parse the correct datetime from the log file name.
Log: fix log saver issue.
> fix: Fix did not auto delete old log issue.

- debian/changelog
- src/library/Makefile
- src/library/inc/resourceutil .h
- src/library/src/resourceutil.c
- src/server/backend/lib/lftmanager.cpp
- src/server/backend/lib/lftmanager.h
If the daemon service take high cpu time more than 3 mins, invoke systemctl to control the CPUQuota. And then reset if rollback to low usage.
Log: Add cpu usage limit.
> feat: Add cpu usage limit.

- src/kernelmod/vfs_kretprobes.c
The strncpy_from_user is sleep function, it may cause block, use copy_from_user replace it.
Log: replace copy user sleep func.
> fix: Fix module call sleep function issue.

- debian/changelog
- src/kernelmod/vfs_kretprobes.c
The mm_segment_t has been remvoed since linux 5.10, fix build issue on higher version.
Log: Fix module build issue.
> fix: Fix module build issue.

- debian/changelog
- debian/control
Fix miss build depend cmake.
Log: Fix deb build.
> fix: Fix miss build depend cmake.

- debian/changelog
- src/server/backend/anythingbackend.cpp
- src/server/backend/lib/lftmanager.cpp
- src/server/backend/lib/lftmanager.h
After it is integrated into file manager daemon, it can not mark process quit. Make it load last index and then rescan after 30s, that make sure the search feature.
Log: fix index issue.
> fix: Fix index load and rescan

- src/kernelmod/vfs_fsnotify.c
After the 5.2 kernel, the data type of the file name in the relevant
data structure has changed from "const unsigned char *" to
"struct qstr", so vfs_monitor also needs to be adjusted accordingly.
Log: adapt new kernel.
> feat: Adapt fsnotify_broadcast to 5.2 kernel

- src/library/CMakeLists.txt
As title.
Log: update CMakeLists file
> chore: Update CMakeLists file

- debian/changelog
> chore: Update version

- src/server/backend/lib/lftmanager.cpp
- src/server/backend/lib/mountcacher.cpp
- src/server/backend/lib/mountcacher.h
As title.
Log: fix deepin-anything-server crash.
Task: https://pms.uniontech.com/task-view-358761.html
> fix: fix _addPathByPartition crash when adding mounts

- src/server/backend/lib/eventadaptor.cpp
As title.
Log: fix deepin-anything-server dbus unresponsive.
Task: https://pms.uniontech.com/task-view-358761.html
> fix: fix anything dbus unresponsive when processing file events

- .reuse/dep5
- debian/control
- debian/deepin-anything-server.install
- rpm/deepin-anything.spec
- src/server/backend/CMakeLists.txt
- src/server/backend/dbusservice/com.deepin.anything.policy
- src/server/backend/lib/lftmanager.cpp
- src/server/backend/lib/lftmanager.h
As title.
Log: enhance security
Task: https://pms.uniontech.com/task-view-355353.html
> feat: add polkit support

- debian/changelog
bump version
Log: bump version
> chore: bump version 6.2.0

- debian/changelog
- src/kernelmod/arg_extractor.c
Adapt kernel module for LOONGARCH architecture.
Log: Adapt kernel module for LOONGARCH architecture.
> feat: Adapt kernel module for LOONGARCH architecture

- src/configs/dbus/AnythingAdaptor.cpp
- src/configs/dbus/AnythingAdaptor.h
Add AnythingAdaptor class generated from qdbusxml2cpp to provide DBus interface for the anything service.
Log: add DBus adaptor for anything service
> chore: add DBus adaptor for anything service
