linuxdeepin/deepin-anything

debian/deepin-anything-dkms.dkms.in
since SUBDIRS is deprecated in Linux 5.0 and will be removed in 5.3
=> Remove SUBDIRS

server/lib/lftmanager.cpp
修复调用不分段搜索时进程崩溃，当maxCount等于-1时，因为count为无符号变量，将导致它的值非常大
=> fix: crash if the maxCount is -1

kernelmod/vfs_utils.c
get_ds was defined as KERNEL_DS since 2.6. It was removed in 5.1.
https://github.com/torvalds/linux/commit/736706bee3298208343a76096370e4f6a5c55915
=> fix: compatibility with 5.1 kernel

server/lib/lftmanager.cpp, server/lib/lftmanager.h
防止在系统启动时创建索引占用io而导致桌面环境启动变慢
默认设置延迟10分钟
=> delay create index data with application start

debian/control, debian/rules
移除 [dh-systemd](https://packages.debian.org/sid/dh-systemd) 依赖
> ### debhelper add-on to handle systemd unit files - transitional package
> This package is for transitional purposes and can be removed safely.
是处理 https://github.com/linuxdeepin/developer-center/issues/3230 问题的一部分。
其它相关：https://github.com/linuxdeepin/dde-file-manager/pull/488
=> chore: remove dh-systemd

debian/control, server/backend/lib/lftdisktool.cpp, server/backend/lib/lftmanager.cpp
When deepin-anything-tool builds the index, it will use the first mount point of the block device instead of the root mount point. Under certain conditions, it is impossible to use the file event to update the index. The solution is to use the root mount point of the block device when deepin-anything-tool builds the index.
Log: Adapt to V23
Bug: https://pms.uniontech.com/bug-view-144735.html
=> fix: search for new files failed due to using wrong mount point

src/server/backend/eventsource_genl.cpp
deepin-anything use the first mount record of the device in /proc/self/mountinfo to construct the file event path, When some partition operations occur, the order of multiple mount records of the same device will change, which leads to an error in the constructed file event path. The solution is to always pick the mount record for the root of the device.
Log: fix bug
=> fix: search fail after partition operation

src/kernelmod/vfs_kretprobes.c, src/library/src/walkdir.c, src/server/backend/lib/lftmanager.cpp
The fuse.dlnfs file system is customized for long file name view for linux, and it has no block device, udisk2 do not support. Filter it for index creating and searching.
Log: support index for dlnfs.
=> feat: support long name fs fuse.dlnfs.

src/kernelmod/Makefile, src/kernelmod/module.c, src/kernelmod/vfs_fsnotify.c, src/kernelmod/vfs_kretprobes.c, src/kernelmod/vfs_log.h, src/kernelmod/vfs_sysfs.c, src/kernelmod/vfs_sysfs.h
Set unnamed devices to monitor via /sys/kernel/vfs_monitor/vfs_unnamed_devices file. Writing "a52" means increasing the monitoring of the device whose device number is 0:52, writing "r52" means removing the monitoring of the device whose device number is 0:52, Write "e0" to unmonitor all unnamed devices.
log: adapt dlnfs
=> feat: Kernel module supports monitoring of unnamed devices

src/server/backend/anythingbackend.cpp, src/server/backend/backend.pro, src/server/backend/eventsource_genl.cpp, src/server/backend/eventsource_genl.h, src/server/backend/lib/daspluginloader.cpp, src/server/backend/lib/daspluginloader.h, src/server/backend/lib/lftdisktool.cpp, src/server/backend/lib/lftdisktool.h, src/server/backend/lib/lftmanager.cpp, src/server/backend/server.cpp, src/server/backend/server.h
Adjust the level of some log content. Set the default log output level, the release version is warning, and the debug version is debug. All logs use category logs, and adjust the category name, no longer use global logs and register corresponding appenders.
log: adjust logging
=> chore: adjust logging

debian/postinst, src/server/backend/dbusservice/com.deepin.anything.conf
fix: a dbus security issue (https://github.com/linuxdeepin/developer-center/issues/3526)
everybody is allowed to own the service on the D-Bus system bus.
Log: fix boo#1136026, https://github.com/linuxdeepin/developer-center/issues/3526
=> fix: a dbus security issue

src/kernelmod/event_merge.c
There is "-Werror=implicit-function-declaration" issue for strcmp function on SW platform, include the miss header file to fix it.
Log: fix dkms build issue.
=> fix: [mod]Fix dkms build error on some platform.

debian/changelog, src/library/Makefile, src/library/inc/resourceutil .h, src/library/src/resourceutil.c
Currectly, the cgroup limit has not been used, use macro exclude it.
Log: fix build issue.
=> fix: fix miss libcgroup depending.

src/kernelmod/arg_extractor.c
Since the 3A5000, kernel CPU config changed to LOONGSON64, the reg is same as loongson3.
Log: fix loongson64.
=> fix: Fix can not get dir_name on loongson64.

debian/changelog, debian/deepin-anything-dkms.postinst, src/kernelmod/arg_extractor.c
If previous dkms deb package has install failed, it does not allow to install anymore, check its status and remove previous dkms dir if failed( status is added).
Log: fix dkms install issue.
=> fix dkms install failed issue. 

src/server/CMakeLists.txt, src/server/backend/CMakeLists.txt
If did not set AUTOMOC on, it will miss a autogen mocs_compilation.cpp file for Qt codes. Add this define in order to fix it.
Log: fix undefined symbol issue.
the error when try dlopen library:
undefined symbol: _ZTVN22deepin_anything_server15AnythingBackendE
=> fix: Fix load library report undefined symbol issue .

debian/changelog, src/server/backend/anythingbackend.h, src/server/backend/lib/eventadaptor.cpp, src/server/backend/lib/eventadaptor.h, src/server/backend/lib/lftmanager.cpp, src/server/backend/lib/lftmanager.h
First, change the 10mins to 30s to build index and limit cpu usage when building. Second, create new task thread and add mutex for index update. Finally, change cpu checking interval to 10s in order to quick response.
Log: Fix cannot search issue after startup.
=> fix: Fix cannot search issue by long time after startup.

src/kernelmod/module.c
Update module init & exit calls to use kernel provided macros, such that they gain correct IBT attributes.
Log: Kernel adaptation
=> fix: Fix obsolete module init/exit

debian/changelog, src/server/backend/anythingbackend.cpp, src/server/backend/lib/lftmanager.cpp
Use exit() instead of abort() when server restart.
Log: Fix server core dump on restart
=> fix: Fix server core dump on restart

debian/changelog, debian/postinst, src/server/backend/lib/lftmanager.cpp, src/server/backend/lib/logsaver.cpp
As title.
Log: fix package install fail
Task: https://pms.uniontech.com/task-view-348801.html
=> fix: Fix install fail caused by postinst execute fail

src/library/src/fs_buf.c, src/server/backend/lib/lftmanager.cpp, src/server/backend/lib/lftmanager.h
Before the fix, the CPU limit check was triggered by a timer, which is unreliable because the main thread could get stuck while executing dbus requests. The solution is to use a separate thread to perform the CPU limit check.
Log: Fix CPU limit check not working
=> fix: Fix CPU limit check not working

src/library/inc/walkdir.h, src/library/src/walkdir.c
The anything server will get the partition list when creating the file index. If the mount path is too long, it will cause a buffer overflow. The solution is to use the dynamic allocation conversion specifier.
Log: fix crash caused by too long mount path
Bug: https://pms.uniontech.com/bug-view-262789.html
=> fix: fix crash caused by too long mount path

src/server/backend/eventsource_genl.cpp, src/server/backend/lib/eventadaptor.cpp, src/server/backend/lib/eventadaptor.h, src/server/backend/lib/lftdisktool.cpp, src/server/backend/lib/mountcacher.cpp, src/server/backend/lib/mountcacher.h
Remove the thread in `EventAdaptor` and use the main thread timer to dispatch events directly. `EventSource_GENL` asynchronously calls `MountCacher::updateMountPoints` to avoid multi-threaded access. Use `Q_GLOBAL_STATIC` to create a singleton, and do not allow static acquisition.
Log: fix deepin-anything-server crash
Bug: https://pms.uniontech.com/bug-view-264761.html
=> fix: fix crash caused by multi-threaded access

src/server/backend/lib/mountcacher.cpp
As title.
Log: fix deepin-anything-server crash.
Task: https://pms.uniontech.com/task-view-358761.html
=> fix: fix findMountPointByPath crash

.reuse/dep5, debian/deepin-anything-server.postinst, debian/deepin-anything-server.service, debian/rules, src/server/app/CMakeLists.txt, src/server/app/deepin-anything-server.service, src/server/app/main.cpp
On V20 system, the service will keep disable status, and the anything server will be started by dde-file-manager-daemon. On V25 system, the service will keep enable status.
Log: support start anything server by systemd service
Bug: https://pms.uniontech.com/bug-view-281871.html
=> feat: support start anything server by systemd service

src/kernelmod/arg_extractor.c
- Optimize recoginizing ARM
* In some distributions, the ARM macro is CONFIG_AARCH64
- Add support for s360x, ppc64le and riscv
=> Add support for s360x, ppc64le and riscv

debian/changelog, src/server/backend/lib/lftmanager.cpp, src/server/backend/lib/logsaver.cpp
Previously, the anything would keep log files generated in the last 30 days. If a large number of logs were generated in a short period of time, it would take up a lot of space. Let's modify it to only keep the 10 most recent log files.
Log: Fix log files take up a lot of space.
=> fix: Fix log files take up a lot of space

debian/changelog, src/library/inc/utils.h, src/library/src/utils.c, src/server/backend/lib/lftmanager.cpp
When the search path does not start with a mount point, the search operation will fail. Let's try to convert the search path to a path under the appropriate mount point before searching.
Log: Fix search fail for invalid path
Bug: https://pms.uniontech.com/bug-view-303925.html
=> fix: Fix search fail for invalid path

debian/changelog, src/server/backend/lib/lftdisktool.cpp, src/server/backend/lib/lftmanager.cpp, src/server/backend/lib/mountcacher.cpp
On immutable system, the root partition is mounted at both "/" and "/sysroot", and subdirectories of the root partition are subsequently mounted at "/". When an application searches, `anything` uses the search path to determine the mount point of the root directory of the corresponding partition. If the search path is "/sysroot/dirname", the mount point returned in this case should be "/sysroot", not "/" as returned by `mnt_get_mountpoint()`.
Log: Fix search fail in immutable system
Bug: https://pms.uniontech.com/bug-view-308297.html
=> fix: Fix search fail in immutable system
